version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run: echo "npm testing"
      - run: npm install
      - run: npm test
  extra_job:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run: echo "An extra super useful step"
workflows:
  version: 2
  build_test_and_coverage:
    jobs:
      - build
      - extra_job
      - test:
          requires:
            - extra_thing
