version: 2
jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Another step"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  multiple_build:
    jobs:
      - build1
      - build2
    